### ISSUE TITLE
Minified js adds four canvases

### ISSUE THREAD

**Issue by Brakebein** [pwambach/angular-canvas-painter#16]
Just a small bug in `angular-canvas-painter.min.js`: where you define the templateCache for `pwCanvasPaint` div, those canvas are also defined causing 4 canvases in the end. So `<div class="pwCanvasPaint" style="position:relative"><canvas id="pwCanvasMain"></canvas><canvas id="pwCanvasTmp" style="position:absolute;top:0;left:0"></canvas></div>` should change to `<div class="pwCanvasPaint" style="position:relative"></div>`. It's only in the minified js file.

**Comment by pwambach** [comment]
Hey, yes i just found out there was a problem with the build process. It is fixed now in version 0.5.1. Thanks for reporting!
