### ISSUE TITLE
Drawing canvas issue on Mobile devices with Modal window bootstrap 

### ISSUE THREAD

**Issue by dilumn** [pwambach/angular-canvas-painter#31]
hi,
I faced an issue with pwCanvas when I include it on a bootstrap modal pop up in mobile devices. For basic modal popups it is working fine. But when you have a scrollable page & at the bottom of the page put a button to pop up a bootstrap modal, temp canvas you used in the library couldn't fine the absolute location to draw.

Any idea why it is behaving like that?

**Comment by dilumn** [comment]
This happened because of a issue in bootstrap modal in mobile devices. I could find the relevant issue in bootstrap repo & found a workaround.

**Comment by mubi64** [comment]
> This happened because of a issue in bootstrap modal in mobile devices. I could find the relevant issue in bootstrap repo & found a workaround.

Hi dilumn can you please let me know the workaround? I am facing the same issue on mobile devices.

**Comment by dilumn** [comment]
@mubi64 ohh this was long time back. If I remember correctly what we did was, upon modal open scroll to the top of the webpage & then stop background scrolling. It was kind of ugly to scroll to the top of the page on modal open because once user close the modal user will be on top of the page not in the scrolled location. But couldn't find any other solution for this issue

**Comment by mubi64** [comment]
I just made a change with your logic that once the modal will be dismissed page will be scrolled to the element from where it was triggered. This workaround resolved my problem. Thanks for the logic.
