### ISSUE TITLE
Load existing image into canvas

### ISSUE THREAD

**Issue by TheNitek** [pwambach/angular-canvas-painter#5]
It would be nice to be able to load an existing image into the canvas by providing a URL. Currently I have to do it in my controller using something like this:

``` javascript
var imageObj = new Image();
imageObj.onload = function () {
 var context = $('#pwCanvasMain').get(0).getContext('2d');
 context.drawImage(this, 0, 0);
};
imageObj.src = 'http://example.org/image.png';
```

**Comment by pwambach** [comment]
Sure would be a nice feature. I'll have a look at it or just create a PR if you want to...

**Comment by pwambach** [comment]
i added an option 'imageSrc' in v0.3.0
