### ISSUE TITLE
add imageSrc width and height

### ISSUE THREAD

**Issue by masdevid** [pwambach/angular-canvas-painter#8]
I love your work,
I do some tweak in order to the image width and height match the canvas container

```
ctx.drawImage(this, 0, 0,options.width,options.height);
```

Could you add another options to change default canvas ID and download image feature?

**Comment by pwambach** [comment]
hey thx for your feedback,

a custom canvas id is a good idea, i will implement it as soon as possible. i could also add an option to stretch the background image like you did.

the image download issue is related to #7. I'm not sure how to solve this the best way and it will take some more time, than the other issues. in the meantime you can access the canvas with it's id (or soon with the custom id ;) ) and get the image data manually.

Cheers
Philipp

**Comment by masdevid** [comment]
Okay, somehow I've managed to add download image by canvas id. But, in my case I need custom canvas Id because I had 2 canvas on the same page and download one of them is impossible if canvas ID is not unique. 
Another feature might be usefull is basic shape tool , so instead add free drawing, why not draw a rectangle/circle to the canvas. I know it's bit hard, but I'm waiting for this since I don't know much about drawing canvas. Thank you.

**Comment by pwambach** [comment]
hey,
check out version 0.3.1 and set the 'customCanvasId' option to give every instance a unique id.

**Comment by max2mx** [comment]
Hey@pwambach, first of all, thank you for the work you have put into this. I have implemented the part for centering the image on the canvas while preserving the aspect ratio. I think adding this would make the project even more feature rich, any thoughts on this?
![screen shot 2016-04-24 at 18 48 07](https://cloud.githubusercontent.com/assets/493844/14768159/143bdfa8-0a4f-11e6-970b-273f974df0b4.png)

**Comment by pwambach** [comment]
Hey @max2mx. Thanks, that sounds great! Can you create a pull request for this?
