### ISSUE TITLE
Offset touch recognized with android browser

### ISSUE THREAD

**Issue by fabersheep** [pwambach/angular-canvas-painter#9]
Hello, I verified that on mobile android browsing the touch position recognition fails, adding a mostly horizontal offset to the touched point. This happens both on a one plus one phone and on a n7 tablet.

On an iPad it behaves correctly. 

I tried with no luck to enable the iOS mode also for android user agents.

If you need i can provide a video of the reproduction.

If i find a solution meanwhile i'll let you know

Best regards
Marco

**Comment by pwambach** [comment]
Hey,

thx for the feedback. On my nexus 4 with android L it works correctly, i will try to reproduce it on other devices. Which Android version did you use?

Cheers
Philipp

**Comment by fabersheep** [comment]
Hello, I just re-tested it with the currently installed version on the nexus 7: android 5.1 with the latest chrome and latest webview installed.

I'm currently downloading the 5.1.1 OTA, but i'm very low on battery, I'll report back once it's done (probably tomorrow)

**Comment by fabersheep** [comment]
I can confirm I still experience the bug with the latest android version on the nexus 7 :(

**Comment by pwambach** [comment]
does the offset error happen also on the example page http://pwambach.github.io/angular-canvas-painter ?

**Comment by fabersheep** [comment]
Right, should've tried this before.

No, it doesn't happens on the demo project. I guess I'm in for a funny
debug session of what makes it crazy. I'm using it into a bootstrap
project, but who knows.

Thank you by now.

On 15 July 2015 at 13:52, Philipp Wambach notifications@github.com wrote:

> does the offset error happen also on the example page
> http://pwambach.github.io/angular-canvas-painter ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pwambach/angular-canvas-painter/issues/9#issuecomment-121590968
> .

## 

Marco Fabbri - Palomar s.r.l.
Divisione Research & Development
http:.//www.palomar.net

COME CONTATTARCI

Assistenza QWin
- _assistenza@palomar.net assistenza@palomar.net_

HW/Sistemistica
- _sistemi@palomar.net sistemi@palomar.net_

Landline

_T 051 6132388_

_F 051 7450755_

**Comment by pwambach** [comment]
do you have an example page where the error occurs?

**Comment by fabersheep** [comment]
Yes, write me at marcofabbri@palomar.net and I can  give you access to a
live example
Il 15/lug/2015 07:45 PM, "Philipp Wambach" notifications@github.com ha
scritto:

**Comment by pwambach** [comment]
actually i found a problem with the touch position calculation. the canvas offset was not correct . i updated to version 0.4.0. Could you check if the problem is solved on your side?

Cheers
Phil

**Comment by fabersheep** [comment]
Yay! I can confirm the bug is gone. It also looks to me that now the canvas
is a little bit more reactive, but perhaps it's unrelated.

Thank you.

p.s. in the 0.4 committed file you forgot to change the version number in
the first line content.

On 16 July 2015 at 18:21, Philipp Wambach notifications@github.com wrote:

> actually i found a problem with the touch position calculation. the canvas
> offset was not correct . i updated to version 0.4.0. Could you check if the
> problem is solved on your side?
> 
> Cheers
> Phil
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pwambach/angular-canvas-painter/issues/9#issuecomment-122009573
> .

## 

Marco Fabbri - Palomar s.r.l.
Divisione Research & Development
http:.//www.palomar.net

COME CONTATTARCI

Assistenza QWin
- _assistenza@palomar.net assistenza@palomar.net_

HW/Sistemistica
- _sistemi@palomar.net sistemi@palomar.net_

Landline

_T 051 6132388_

_F 051 7450755_
